/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GSLJava_GSLOps */

#ifndef _Included_GSLJava_GSLOps
#define _Included_GSLJava_GSLOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GSLJava_GSLOps
 * Method:    gslSfBesselJ0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_GSLJava_GSLOps_gslSfBesselJ0
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
