/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CUDASig_CUDASig */

#ifndef _Included_CUDASig_CUDASig
#define _Included_CUDASig_CUDASig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CUDASig_CUDASig
 * Method:    cudadwt
 * Signature: ([FI[F)V
 */
JNIEXPORT void JNICALL Java_CUDASig_CUDASig_cudadwt
  (JNIEnv *, jobject, jfloatArray, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
