/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NROps_NROps */

#ifndef _Included_NROps_NROps
#define _Included_NROps_NROps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NROps_NROps
 * Method:    cnrfft
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_NROps_NROps_cnrfft
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     NROps_NROps
 * Method:    nfourn
 * Signature: ([D[III)V
 */
JNIEXPORT void JNICALL Java_NROps_NROps_nfourn
  (JNIEnv *, jobject, jdoubleArray, jintArray, jint, jint);

/*
 * Class:     NROps_NROps
 * Method:    mul
 * Signature: ([DII[DI[D)V
 */
JNIEXPORT void JNICALL Java_NROps_NROps_mul
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
