/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CCOps_CCOps */

#ifndef _Included_CCOps_CCOps
#define _Included_CCOps_CCOps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CCOps_CCOps
 * Method:    pt
 * Signature: ([DII[DI[D)V
 */
JNIEXPORT void JNICALL Java_CCOps_CCOps_pt
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     CCOps_CCOps
 * Method:    solv
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_solv
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    solvps
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_solvps
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    solvtd
 * Signature: ([D[D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_solvtd
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    solvru
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_solvru
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    svduv
 * Signature: ([D[D[DI[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_svduv
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    sv2u1v
 * Signature: ([D[DI[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_sv2u1v
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    sv2uv
 * Signature: ([D[D[DI[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_sv2uv
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    sv2val
 * Signature: ([D[DII)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_sv2val
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    svdval
 * Signature: ([D[DII)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_svdval
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    minv
 * Signature: ([DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_minv
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    psinv
 * Signature: ([DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_psinv
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    ruinv
 * Signature: ([DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_ruinv
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    eigval
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_eigval
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    eigen
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_eigen
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    evmax
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_evmax
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    smgen
 * Signature: ([D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_smgen
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    ortho
 * Signature: ([DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_ortho
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    ccfft
 * Signature: ([D[D[DI)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_ccfft
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    pwspec
 * Signature: ([DII)I
 */
JNIEXPORT jint JNICALL Java_CCOps_CCOps_pwspec
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     CCOps_CCOps
 * Method:    qrlsq
 * Signature: ([D[DII[I)D
 */
JNIEXPORT jdouble JNICALL Java_CCOps_CCOps_qrlsq
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
